### ISSUE TITLE
Refresh JWT token before timeout

### ISSUE THREAD

**Issue by Alxandr** [mongoose-os-libs/gcp#2]
The JWT tokens used with GCP times out. The timeout is configurable, but only up to a maximum of 24 hrs according to [docs](https://cloud.google.com/iot/docs/how-tos/credentials/jwts#jwt_claims). My main issue is that when the timeout occurs, I get errors in my dashboard, even though the client immediately reconnects and it's not a problem for the device. Having a timer that kicks in about 30 seconds before the token expires, and refreshing it is probably a good solution to this issue. It should not cause much extra work for the devices, because when the token expires, the connection is dropped, and the client has to re-generate a token regardless.

**Comment by rojer** [comment]
ok, that's new. i don't remember there being any mention of refreshing the token without disconnecting before.

however... i also don't see it now. each of the sample code snippets destroys the client and then re-creates it. i can't see how that achieves the stated goal of reconnecting without disconnecting the device. do you?

**Comment by Alxandr** [comment]
The stated goal is not to reconnect without disconnecting. It's simply to not have an error on the server side. As is, the client attempts to use the old JWT, the server logs an error and closes the connection (at least from what I understand). I'd like instead for the client to close the connection (when the timeout occurs), and then reopen a new one. Cause as far as I understood, you can only specify the token on connect.

**Comment by rojer** [comment]
> you can only specify the token on connect.

yes, it is transmitted as part of initial CONNECT message which cannot be repeated without closing the connection. but i see your point - in anticipation of token expiration, close the connection cleanly and reconnect immediately. yes, this can be done, we just need a one-shot timer that drops the connection before the token expires and the reconnection logic will do the rest.

**Comment by Alxandr** [comment]
@rojer Yep. And this exactly was my request. I'd be glad to PR it myself if I knew how timers worked in mongoose-os 😛.

**Comment by cpq** [comment]
https://github.com/cesanta/mongoose-os/blob/master/fw/include/mgos_timers.h
