### ISSUE TITLE
Enable travis builds of library

### ISSUE THREAD

**Issue by Alxandr** [mongoose-os-libs/gcp#4]
See https://github.com/YoloDev/remote-config/blob/master/.travis.yml for sample working travis setup for mongoose libraries. This will automatically build all PRs, to ensure that nothing is broken (or rather, that it compiles against all platforms at least).

**Comment by cpq** [comment]
Looks great ! The libs, however, cannot be built, only apps can.
There should be some way to build a test app with this lib - maybe a temporary generated app?

**Comment by Alxandr** [comment]
Libs can be built. The thing I linked to is a lib.

**Comment by cpq** [comment]
Ah, yeah, sorry. I got myself out of date :)

**Comment by Alxandr** [comment]
In all honesty, all that would be needed would be to copy that config file, and enable Travis for this (and the other) library projects.

**Comment by rojer** [comment]
so, i've set up travis builds for apps that use this library - https://github.com/mongoose-os-apps/demo-c/commit/4694b96c00af16e4ab84298dac91c20cf6ff1666 and https://github.com/mongoose-os-apps/demo-js/commit/71ea2aa7d2d237814eb564ff16f819ef16ba3fa1

i don't know if it makes sense to set up builds for every single library on its own, well see about that in the future.
in general, we are now trying to move from our private CI to Travis, so there will be more to come on that front. thanks for the inspiration!
