### ISSUE TITLE
How to call RPC commands via MQTT server?

### ISSUE THREAD

**Issue by evilandfox** [mongoose-os-libs/gcp#5]
I tried this
`mos --port mqtts://mqtt.googleapis.com:8883/esp8266_1459A7 call Config.Get`
But got
```
E1014 15:14:38.938000    2540 reconnect_wrapper.go:93] [reconnectWrapperCodec to mqtts://mqtt.googleapis.com:8883/esp8266_1459A7; connect in 2.00s] connection error: MQTT connect error: Unnacceptable protocol version
Unnacceptable protocol version
```
Is that possible?

**Comment by rojer** [comment]
unfortunately, currently it is not possible to invoke RPC methods on the device via GCP
this is because GCP does not provide bi-directional MQTT<->PubSub communication, only device can publish messages.
