### ISSUE TITLE
Google's minimal root CA

### ISSUE THREAD

**Issue by tripflex** [mongoose-os-libs/gcp#6]
https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#downloading_mqtt_server_certificates

It looks as though Google has a minimal root CA set (<1 KB) for `mqtt.2030.ltsapis.goog` (instead of the `mqtt.googleapis.com` that is being used.

Because the majority of MOS devices are very limited on space, shouldn't we move the GCP library away from using the bloated `ca-bundle` (which includes certs for Amazon, Azure, and others), to use only this specific minimal certificates, and the LTS domain (which is specifically for devices that Mongoose OS is targeted at)

If you download the certs from Google they are not in human readable format, so for reference here they are.  You can do this yourself by running this command:

```
openssl x509 -in gtsltsr.crt -inform der -out gtsltsr.pem -outform PEM
openssl x509 -in GSR4.crt -inform der -out GSR4.pem -outform PEM
```

https://stackoverflow.com/questions/5215771/how-can-i-check-if-the-certificate-file-i-have-is-in-pem-format

Here's the `gtsltsr.pem` in human readable format:
```
-----BEGIN CERTIFICATE-----
MIIBxTCCAWugAwIBAgINAfD3nVndblD3QnNxUDAKBggqhkjOPQQDAjBEMQswCQYD
VQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzERMA8G
A1UEAxMIR1RTIExUU1IwHhcNMTgxMTAxMDAwMDQyWhcNNDIxMTAxMDAwMDQyWjBE
MQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExM
QzERMA8GA1UEAxMIR1RTIExUU1IwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATN
8YyO2u+yCQoZdwAkUNv5c3dokfULfrA6QJgFV2XMuENtQZIG5HUOS6jFn8f0ySlV
eORCxqFyjDJyRn86d+Iko0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUw
AwEB/zAdBgNVHQ4EFgQUPv7/zFLrvzQ+PfNA0OQlsV+4u1IwCgYIKoZIzj0EAwID
SAAwRQIhAPKuf/VtBHqGw3TUwUIq7TfaExp3bH7bjCBmVXJupT9FAiBr0SmCtsuk
miGgpajjf/gFigGM34F9021bCWs1MbL0SA==
-----END CERTIFICATE-----
```

Here's the `GSR4.crt` in human readable format:
```
-----BEGIN CERTIFICATE-----
MIIB4TCCAYegAwIBAgIRKjikHJYKBN5CsiilC+g0mAIwCgYIKoZIzj0EAwIwUDEk
MCIGA1UECxMbR2xvYmFsU2lnbiBFQ0MgUm9vdCBDQSAtIFI0MRMwEQYDVQQKEwpH
bG9iYWxTaWduMRMwEQYDVQQDEwpHbG9iYWxTaWduMB4XDTEyMTExMzAwMDAwMFoX
DTM4MDExOTAzMTQwN1owUDEkMCIGA1UECxMbR2xvYmFsU2lnbiBFQ0MgUm9vdCBD
QSAtIFI0MRMwEQYDVQQKEwpHbG9iYWxTaWduMRMwEQYDVQQDEwpHbG9iYWxTaWdu
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEuMZ5049sJQ6fLjkZHAOkrprlOQcJ
FspjsbmG+IpXwVfOQvpzofdlQv8ewQCybnMO/8ch5RikqtlxP6jUuc6MHaNCMEAw
DgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFFSwe61F
uOJAf/sKbvu+M8k8o4TVMAoGCCqGSM49BAMCA0gAMEUCIQDckqGgE6bPA7DmxCGX
kPoUVy0D7O48027KqGx2vKLeuwIgJ6iFJzWbVsaj8kfSt24bAgAXqmemFZHe+pTs
ewv4n4Q=
-----END CERTIFICATE-----
```

Sorta related to #1

**Comment by tripflex** [comment]
Even looking at commits on this repo, before azure, losant, and it was 18.4kb
https://github.com/mongoose-os-libs/ca-bundle/blob/eb4918847860eb47ea3586c1bc3636ec3ec3797d/fs/ca.pem

Now the file is 26.5kb:
https://github.com/mongoose-os-libs/ca-bundle/blob/master/fs/ca.pem

That's like 8kb of space being used for certs that Google IoT clients will not even be using ... just seems this library is bloated with certs that may never be used.

My issue is that once I then setup GCP, and then enable encryption .. space is so limited, sometimes it just fails on encryption due to not enough space to encrypt files during the process

**Comment by rojer** [comment]
ultimately, i think, the bundle should be unbundled and we should have each library add its own ca file and mos (mbedtls, really) to be able to check them all. e.g., set `ca_cert="*ca.pem"`, so it will match `gcp.ca.pe`, `aws.ca.pem` and make adding your own ca files easy - just call it `something.ca.pem` and it will match. but it requires change to mbedtls, somewhat non-trivial.
so, for now i think we'll just have to add another cert to the bundle.

**Comment by tripflex** [comment]
@rojer yeah i agree i think it would be good to have each library with its own bundle .. as really that's the way it should be to minimize space usage
